// A record class in Java is a special kind of class that is used to create immutable data classes. It is a shorthand way of creating a class that only has data fields and no other methods. The compiler automatically generates the constructor, getters, toString, equals, and hashCode methods for a record class.
record Person(String name, int age) {
    // The fields of the record class are declared in the record header. In this case, the record class has two fields: name and age.
    // The fields of a record class are implicitly final and cannot be modified after the object is created.
    // The fields of a record class can be accessed using the getter methods that are automatically generated by the compiler. In this case, the getter methods are name() and age().
}
public class RecordClass {
    public static void main(String[] args) {

        Person person = new Person("John", 30);
        System.out.println(person.name());//here we are using the getter method to access the name field of the record class.
        System.out.println(person.age());//here we are using the getter method to access the age field of the record class.
        System.out.println(person);//here we are using the toString method to print the record class object. The toString method is automatically generated by the compiler and it returns a string representation of the record class object.
        
    }
}
